version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: npm
    versions:
    - 7.10.0
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
    - 7.6.3
    - 7.7.0
    - 7.7.4
    - 7.7.5
    - 7.7.6
    - 7.8.0
    - 7.9.0
  - dependency-name: eslint-plugin-sonarjs
    versions:
    - 0.6.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: angular-cesium
    versions:
    - 0.0.66
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.901.13
    - 0.901.14
